### ISSUE TITLE
Recovery from lost database connection

### ISSUE THREAD

**Issue by psiotwo** [kbss-cvut/jopa#78] opened 2020-09-18 10:46 UTC
Currently, when JOPA loses connection, it throws an exception. A retrial strategy was implemented as a part of https://github.com/kbss-cvut/jopa/issues/72, which tackles this a bit.

However, when connection is lost to the triple store, no recovery happens, however, requiring the app using JOPA to be restarted. 

The goal of this ticket is to enable recovery from lost connections/network errors.

**Comment by ledsoft** [comment] 2020-09-18 11:47
Unable to reproduce, application with JOPA is able to continue working when connection is regained.

Closing for now, feel free to reopen once a reproducible example is available.

**Closed by ledsoft** 2020-09-18 11:47 UTC
Labels: feature, invalid
