### ISSUE TITLE
JOPA does not work with GraphDB 8

### ISSUE THREAD

**Issue by psiotwo** [kbss-cvut/jopa#11] opened 2017-11-27 16:04 UTC
GraphDB 8 as a back-end, using RDF4J connector, does not work.
When reading an entity using EntityManager.find, JOPA freezes.

**Comment by ledsoft** [comment] 2017-11-28 12:56
Unable to reproduce with GraphDB 8.3.1.

**Comment by ledsoft** [comment] 2017-12-02 10:41
Closing for now. Reopen if a reproducible case is available.

**Closed by ledsoft** 2017-12-02 10:41 UTC
